name: site_monitor
description: Site Monitor - Monitor websites and APIs uptime.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  intl: ^0.19.0
  firebase_core: ^2.25.0
  firebase_messaging: ^14.7.0
  connectivity_plus: ^6.0.3

  # For JSON (if needed)
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
